library(haven)
GSS2016 <- read_sav("GSS2016.sav")

library(dplyr)
g_df <- select(GSS2016, PARTYID, PRES12, POLVIEWS, SIZE,
               SIZE, AGE, CHILDS, RACE, NATSPAC, NATENVIR,
               NATHEAL, NATCITY, NATDRUG, NATEDUC, NATRACE,
               NATAID, NATARMS, NATFARE, NATROAD, NATSOC, NATMASS,
               NATPARK, NATCHLD, NATSCI, NATENRGY, TAX,
               SPKATH, COLATH, LIBATH, SPKCOM, COLCOM, LIBCOM,
               SPKMIL, COLMIL, LIBMIL, SPKHOMO, COLHOMO, LIBHOMO,
               SPKRAC, COLRAC, LIBRAC, SPKMSLM, COLMSLM, LIBMSLM,
               REVSPEAK, REVPUB, TWITTER, INSTAGRM, LINKEDIN,
               FACEBOOK, SNAPCHAT, TUMBLR, WHATSAPP, GOOGLESN, 
               PINTERST, FLICKR, VINE, CLSSMTES, INTWKDYH,
               INTWKENH)
